name: Publish

on: 
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Clone
        uses: actions/checkout@v2

      - name: Pack
        run: dotnet pack -c Release src/Artemis.GameFinder/Artemis.GameFinder.csproj

      - name: Upload
        run: dotnet nuget push src/Artemis.GameFinder/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
